DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS payables;
DROP TABLE IF EXISTS receivables;

CREATE TABLE account (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  amount DECIMAL(19, 4) NOT NULL,
  currency CHAR(3) NOT NULL
);

CREATE TABLE payables (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  amount DECIMAL(19, 4) NOT NULL,
  currency CHAR(3) NOT NULL,
  row_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE receivables (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  amount DECIMAL(19, 4) NOT NULL,
  currency CHAR(3) NOT NULL,
  row_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (account_id) REFERENCES account(id)
);
